<div class="span5">
    <h2>Découvrez le livre consacré au Zend Framework 2</h2><br />
    <img class="thumbnail" src="/img/couv.png" style="margin-bottom: 15px;" />
    <p>"Au coeur de Zend Framework 2" analyse le fonctionnement du coeur du framework et propose un cas d'utilisation complet.</p>
    <p>Retrouvez plus de détails sur le site consacré au <a href="http://au-coeur-de-zend-framework-2.fr/">livre sur le Zend Framework 2</a></p>
</div>