<div class="row">
    <div class="span7">
    	<h2>Contact</h2><br />
        <?php echo $this->messages(array('valid', 'error')); ?>
        <?php
            $form = $this->form;
            $form->prepare();
            $form->setAttribute('action', $this->url());
            $form->setAttribute('method', 'post');
            echo $this->form()->openTag($form);
        ?>
        <dl class="zend_form">
            <?php echo $this->formRow($form->get('web_identity')->get('name')); ?>
            <?php echo $this->formRow($form->get('web_identity')->get('firstname')); ?>
            <?php echo $this->formRow($form->get('web_identity')->get('email')); ?>
            <?php echo $this->formRow($form->get('simple_message')->get('subject')); ?>
            <?php echo $this->formRow($form->get('simple_message')->get('message')); ?>
            <?php echo $this->formRow($form->get('send')); ?>
        </dl>
        <?php echo $this->form()->closeTag() ?>
    </div>
    <?php echo $this->render('bloc/book'); ?>
</div>