<div class="row">
    <div class="span7">
    	<h2>Contact</h2><br />
        <?php echo $this->messages(array('valid', 'error')); ?>
        <?php
            $form = $this->form;
            $form->prepare();
            $form->setAttribute('action', $this->url());
            $form->setAttribute('method', 'post');
            echo $this->form()->openTag($form);
        ?>
        <dl class="zend_form">
            <dt>
                <?php echo $this->formLabel($form->get('web_identity')->get('name')); ?>
            </dt>
            <dd>
                <?php
                    echo $this->formInput($form->get('web_identity')->get('name'));
                    echo $this->formElementErrors($form->get('web_identity')->get('name'));
                ?>
            </dd>
            <dt>
                <?php echo $this->formLabel($form->get('web_identity')->get('firstname')); ?>
            </dt>
            <dd>
                <?php
                    echo $this->formInput($form->get('web_identity')->get('firstname'));
                    echo $this->formElementErrors($form->get('web_identity')->get('firstname'));
                ?>
            </dd>
            <dt>
                <?php
                    echo $this->formLabel($form->get('web_identity')->get('email'));
                ?>
            </dt>
            <dd>
                <?php
                    echo $this->formInput($form->get('web_identity')->get('email'));
                    echo $this->formElementErrors($form->get('web_identity')->get('email'));
                ?>
            </dd>
            <dt>
                <?php echo $this->formLabel($form->get('simple_message')->get('subject')); ?>
            </dt>
            <dd>
                <?php
                    echo $this->formInput($form->get('simple_message')->get('subject'));
                    echo $this->formElementErrors($form->get('simple_message')->get('subject'));
                ?>
            </dd>
            <dt>
                <?php echo $this->formLabel($form->get('simple_message')->get('message')); ?>
            </dt>
            <dd>
                <?php
                    echo $this->formTextarea($form->get('simple_message')->get('message'));
                    echo $this->formElementErrors($form->get('simple_message')->get('message'));
                ?>
            </dd>
            <dt>
                <?php echo $this->formLabel($form->get('send')); ?>
            </dt>
            <dd>
                <?php
                    echo $this->formElement($form->get('send'));
                ?>
            </dd>
        </dl>
        <?php echo $this->form()->closeTag() ?>
    </div>
    <?php echo $this->render('bloc/book'); ?>
</div>