<div class="row">
    <h2>Tweet sur Zend Framework</h2><br />
    <div class="span12">
        <?php foreach($tweets as $tweet) : ?>
            <p>
                <?php echo $this->usertwitter($tweet->user); ?> : <?php echo $tweet->text; ?>
            </p>
        <?php endforeach; ?>
        <?php /*echo $this->paginationControl($tweetsen);*/ ?>
        <?php echo $this->render('bloc/paginator'); ?>
    </div>
</div>